minimum_pre_commit_version: 2.3.0


repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: ruff check
        pass_filenames: false
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
      - id: isort
        name: isort
        language: system
        entry: isort
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: CHANGELOG.md
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: (?x)^(
            tests/.+|
            deployment/.+
          )
