# Nucleus overview: https://paylocity.atlassian.net/wiki/spaces/NUC/overview
# Documentation on what this file does: https://paylocity.atlassian.net/l/cp/KPQ0ksnu
# Detailed descriptions of each field: https://paylocity.atlassian.net/wiki/x/sg7SAg
# Sections with <> are meant to be replaced.

# This section governs the software component of a project; the code behind an API's interface layer
# or running in a Databricks batch process.
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: <yourmalcodelowercase>-service
  
  title: <Human Readable Title>
  description: <Description here>
  labels:
    paylocity.com/api-version: v1
  annotations:
    jira.com/project-slug: DSWS
    teamcity.com/project-slug: DataScience_<MyTeamCitySubProjectName>
    hal.paylocity.com/application-code-id: "<HAL_id_here>"
  # Samples, please overwrite
  links:
  - url: https://paylocity.atlassian.net/wiki/spaces/DataScience/pages/144900404/Overall+Diagram
    title: Architecture Diagram
  - url: https://paylocity.atlassian.net/wiki/spaces/PR/pages/121433835/RFC%3A+Scaling+Recommendations+Across+Products
    title: Data Science RFC
spec:
  type: service
  lifecycle: development
  owner: data-science
  providesApis:
  - api:default/<YourMalCodeHere>
  consumesApis: []
  dependsOn: []
  custom:
    deploymentLocation: "aws-greenfield"
